# -*- coding: utf-8 -*-
"""demographic_data_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OYjPfEXXZfwMi5S2jEsvrkSZh1nZQq3
"""

import pandas as pd
import numpy as np

df = pd.read_csv('adult_data.csv')
df.head(2)

#1

df['race'].value_counts()

#2

df[['sex', 'age']]
df[df.sex == 'Male']['age'].mean()

#3

num_of_bar = df[df['education'] == 'Bachelors'].value_counts().sum()
num_of_bar

num_of_bar / df.value_counts().sum() * 100

#4

ad_edu = df[(df['education'] == 'Bachelors') |(df['education'] =='Doctorate') | (df['education'] =='Masters')]
g_sal = ad_edu[ad_edu['salary'] ==  '>50K'].value_counts().sum()

g_sal / ad_edu.value_counts().sum() * 100

#5

not_ad_edu = df[(df['education'] != 'Bachelors') & (df['education'] != 'Doctorate') & (df['education'] != 'Masters')]
not_ad_sal = not_ad_edu[not_ad_edu['salary'] ==  '>50K'].value_counts().sum()

not_ad_sal / not_ad_edu.value_counts().sum() *100

#6
df['hours-per-week'].min()

#7

min_hrs = df[df['hours-per-week'] == df['hours-per-week'].min()]
min_hrs_sal = min_hrs[min_hrs['salary'] == '>50K'].value_counts().sum()

min_hrs_sal / min_hrs.value_counts().sum() * 100

#8

sal_g50 = df[df['salary'] == '>50K']
country = pd.DataFrame(sal_g50['native-country'].value_counts())

tot_num = sal_g50['native-country'].value_counts().sum()
val = country['count'].values

country["Percentage"] = val / tot_num * 100
country.head(3)

#9

indians = df[df['native-country'] == 'India']
indians_sal = indians[indians['salary'] == '>50K']

pop_ocupation = indians_sal['occupation'].value_counts().iloc[0:5]
pop_ocupation