# -*- coding: utf-8 -*-
"""mean_var_std.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xL9Lj6K4x5WnOkFE9ATKlxxz24IKrb5A
"""

import pandas as pd
import numpy as np

x = np.array([0,1,5,2,3,4,5,6,7,8])
x

def calculate(arr):
  try:
    x = arr.reshape(3,3)
    s = {'mean' : [x.mean(axis=0).tolist(),x.mean(axis=1).tolist(),x.mean().tolist()],
        'variance' : [x.var(axis=0).tolist(), x.var(axis=1).tolist(), x.var().tolist()],
        'standard deviation': [x.std(axis=0).tolist(), x.std(axis=1).tolist(), x.std().tolist()],
        'max' : [x.max(axis=0).tolist(), x.max(axis=1).tolist(), x.max().tolist()],
        'min' : [x.min(axis=0).tolist(), x.min(axis=1).tolist(), x.min().tolist()],
        'sum' : [x.sum(axis=0).tolist(), x.sum(axis=1).tolist(), x.sum().tolist()]
        }
  except ValueError:
    s = 'List must contain nine numbers.'
  return s

f = calculate(x)
f

