# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zB_rS1BOFAGfFWdKEmuoFhK9AQgB1-W4
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib
import numpy as np

model = joblib.load('model.joblib')
app = FastAPI()

class Item(BaseModel):
    size: float

@app.post("/predict")
def predict(item: Item):
  X = np.array([item.size]).reshape(-1, 1)
  y_pred = model.predict(X)
  return {"prediction": float(y_pred[0])}

